#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
# sudo yabai --load-sa
#

# global settings
yabai -m config                                 \
    external_bar                 all:40:0       \
    menubar_opacity              1.0            \
    display_arrangement_order    default        \
    window_shadow                on             \
    window_opacity               off            \
    window_origin_display        default        \
    active_window_opacity        1.0            \
    normal_window_opacity        0.80           \
    window_placement             second_child   \
    window_zoom_persist          on             \
    window_animation_duration    0.5            \
    window_animation_easing      ease_out_circ  \
    window_opacity_duration      0.2            \
    insert_feedback_color        0xff9dd274     \
    split_ratio                  0.75           \
    split_type                   auto           \
    auto_balance                 off             \
    top_padding                  8             \
    bottom_padding               8             \
    left_padding                 8             \
    right_padding                8             \
    window_gap                   10             \
    layout                       bsp            \
    mouse_modifier               alt            \
    mouse_action1                move           \
    mouse_action2                resize         \
    mouse_follows_focus          off            \
    focus_follows_mouse          off            \
    mouse_drop_action            swap

    
# ===== Rules ==================================
yabai -m rule --add app="^App Store$" manage=off
# yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^Finder$" sticky=on layer=above manage=off
yabai -m rule --add app="System Settings" manage=off
yabai -m rule --add app="^System Information$" sticky=on layer=above manage=off
yabai -m rule --add app="^Activity Monitor$" sticky=on layer=above manage=off
yabai -m rule --add label="System Preferences" app="^System Preferences$" manage=off

yabai -m rule --add app="^飞书$" sticky=on layer=above manage=off
yabai -m rule --add app="^Feishu$" sticky=on layer=above manage=off
yabai -m rule --add app="^Lark$" sticky=on layer=above manage=off
yabai -m rule --add app="^Lark Meetings$" sticky=on layer=above manage=off
yabai -m rule --add app="^Seal$" sticky=on layer=above manage=off
yabai -m rule --add app="^AppCleaner$" sticky=off layer=above manage=off
yabai -m rule --add app="^Karabiner-Elements$" sticky=on layer=above manage=off
yabai -m rule --add app="^Karabiner-EventViewer$" sticky=on layer=above manage=off
# yabai -m rule --add app="^Things$" manage=off
# yabai -m rule --add app="^Bartender 5$" manage=off
# yabai -m rule --add app="^Magnet$" manage=off
yabai -m rule --add app="^WeChat$" manage=off
yabai -m rule --add app="^微信$" manage=off
yabai -m rule --add app="^Clash for Windows$" manage=off
yabai -m rule --add app="Dash" manage=off
yabai -m rule --add app="^WeCom$" manage=off
yabai -m rule --add app="^企业微信$" manage=off
yabai -m rule --add app="^BaiduIM$" manage=off

yabai -m rule --add app="^Pieces$" manage=off
yabai -m rule --add app="^Loopback$" manage=off
yabai -m rule --add app="^钉钉$" manage=off
yabai -m rule --add app="^DingTalk$" manage=off

#yabai -m rule --add app="^GoLand$" title!="^(Settings)$" manage=off
# 使 GoLand 的其他窗口不浮动
yabai -m rule --add app="^GoLand$" title!="^Settings$" manage=on
# 使 GoLand 的常用窗口浮动
yabai -m rule --add app="^GoLand$" title="^Settings$" manage=off
yabai -m rule --add app="^GoLand$" title="^(Add File to Git)$" manage=off
yabai -m rule --add app="^GoLand$" title="^Delete$" manage=off
yabai -m rule --add app="^GoLand$" title="^Deployment$" manage=off
yabai -m rule --add app="^GoLand$" title="^(New Project)$" manage=off
yabai -m rule --add app="^GoLand$" title="^(Create Class)$" manage=off
yabai -m rule --add app="^GoLand$" title="^(Project Structure)$" manage=off
yabai -m rule --add app="^GoLand$" title="^(Local History: )$" manage=off
yabai -m rule --add app="^GoLand$" title="^(Create Run Configuration: )$" manage=off
yabai -m rule --add app="^GoLand$" title="^(Run Target)$" manage=off
yabai -m rule --add app="^GoLand$" title="^(Run/Debug Configurations)$" manage=off


# 使 IntelliJ IDEA 的其他窗口不浮动
yabai -m rule --add app="^IntelliJ IDEA$" title!="^Settings$" manage=on
# 使 IntelliJ IDEA 的设置窗口浮动
yabai -m rule --add app="^IntelliJ IDEA$" title="^Settings$" manage=off
yabai -m rule --add app="^IntelliJ IDEA$" title="^(Add File to Git)$" manage=off
yabai -m rule --add app="^IntelliJ IDEA$" title="^Delete$" manage=off
yabai -m rule --add app="^IntelliJ IDEA$" title="^Deployment$" manage=off
yabai -m rule --add app="^IntelliJ IDEA$" title="^(New Project)$" manage=off
yabai -m rule --add app="^IntelliJ IDEA$" title="^(Create Class)$" manage=off
yabai -m rule --add app="^IntelliJ IDEA$" title="^(Project Structure)$" manage=off
yabai -m rule --add app="^IntelliJ IDEA$" title="^(Local History: )$" manage=off
yabai -m rule --add app="^IntelliJ IDEA$" title="^(Create Run Configuration: )$" manage=off
yabai -m rule --add app="^IntelliJ IDEA$" title="^(Run Target)$" manage=off
yabai -m rule --add app="^IntelliJ IDEA$" title="^(Run/Debug Configurations)$" manage=off

# 使 IntelliJ IDEA 的其他窗口不浮动
yabai -m rule --add app="^IntelliJ IDEA-EAP$" title!="^Settings$" manage=on
# 使 IntelliJ IDEA 的设置窗口浮动
yabai -m rule --add app="^IntelliJ IDEA-EAP$" title="^Settings$" manage=off
yabai -m rule --add app="^IntelliJ IDEA-EAP$" title="^Settings$" manage=off
yabai -m rule --add app="^IntelliJ IDEA-EAP$" title="^(Add File to Git)$" manage=off
yabai -m rule --add app="^IntelliJ IDEA-EAP$" title="^Delete$" manage=off
yabai -m rule --add app="^IntelliJ IDEA-EAP$" title="^Deployment$" manage=off
yabai -m rule --add app="^IntelliJ IDEA-EAP$" title="^(New Project)$" manage=off
yabai -m rule --add app="^IntelliJ IDEA-EAP$" title="^(Create Class)$" manage=off
yabai -m rule --add app="^IntelliJ IDEA-EAP$" title="^(Project Structure)$" manage=off
yabai -m rule --add app="^IntelliJ IDEA-EAP$" title="^(Local History: )$" manage=off
yabai -m rule --add app="^IntelliJ IDEA-EAP$" title="^(Create Run Configuration: )$" manage=off
yabai -m rule --add app="^IntelliJ IDEA-EAP$" title="^(Run Target)$" manage=off
yabai -m rule --add app="^IntelliJ IDEA-EAP$" title="^(Run/Debug Configurations)$" manage=off


# 使 WebStorm 的其他窗口不浮动
yabai -m rule --add app="^WebStorm$" title!="^Settings$" manage=on
# 使 WebStorm 的设置窗口浮动
yabai -m rule --add app="^WebStorm$" title="^Settings$" manage=off
yabai -m rule --add app="^WebStorm$" title="^(Add File to Git)$" manage=off
yabai -m rule --add app="^WebStorm$" title="^Delete$" manage=off
yabai -m rule --add app="^WebStorm$" title="^Deployment$" manage=off
yabai -m rule --add app="^WebStorm$" title="^(New Project)$" manage=off
yabai -m rule --add app="^WebStorm$" title="^(Create Class)$" manage=off
yabai -m rule --add app="^WebStorm$" title="^(Project Structure)$" manage=off
yabai -m rule --add app="^WebStorm$" title="^(Local History: )$" manage=off
yabai -m rule --add app="^WebStorm$" title="^(Create Run Configuration: )$" manage=off
yabai -m rule --add app="^WebStorm$" title="^(Run Target)$" manage=off
yabai -m rule --add app="^WebStorm$" title="^(Run/Debug Configurations)$" manage=off

# 使 PhpStorm 的其他窗口不浮动
yabai -m rule --add app="^PhpStorm$" title!="^Settings$" manage=on
# 使 PhpStorm 的设置窗口浮动
yabai -m rule --add app="^PhpStorm$" title="^Settings$" manage=off
yabai -m rule --add app="^PhpStorm$" title="^(Add File to Git)$" manage=off
yabai -m rule --add app="^PhpStorm$" title="^Delete$" manage=off
yabai -m rule --add app="^PhpStorm$" title="^Deployment$" manage=off
yabai -m rule --add app="^PhpStorm$" title="^(New Project)$" manage=off
yabai -m rule --add app="^PhpStorm$" title="^(Create Class)$" manage=off
yabai -m rule --add app="^PhpStorm$" title="^(Project Structure)$" manage=off
yabai -m rule --add app="^PhpStorm$" title="^(Local History: )$" manage=off
yabai -m rule --add app="^PhpStorm$" title="^(Create Run Configuration: )$" manage=off
yabai -m rule --add app="^PhpStorm$" title="^(Run Target)$" manage=off
yabai -m rule --add app="^PhpStorm$" title="^(Run/Debug Configurations)$" manage=off

# 使 Rust Rover 的其他窗口不浮动
yabai -m rule --add app="^Rust Rover$" title!="^Settings$" manage=on
# 使 Rust Rover 的设置窗口浮动
yabai -m rule --add app="^Rust Rover$" title="^Settings$" manage=off
yabai -m rule --add app="^Rust Rover$" title="^(Add File to Git)$" manage=off
yabai -m rule --add app="^Rust Rover$" title="^Delete$" manage=off
yabai -m rule --add app="^Rust Rover$" title="^Deployment$" manage=off
yabai -m rule --add app="^Rust Rover$" title="^(New Project)$" manage=off
yabai -m rule --add app="^Rust Rover$" title="^(Create Class)$" manage=off
yabai -m rule --add app="^Rust Rover$" title="^(Project Structure)$" manage=off
yabai -m rule --add app="^Rust Rover$" title="^(Local History: )$" manage=off
yabai -m rule --add app="^Rust Rover$" title="^(Create Run Configuration: )$" manage=off
yabai -m rule --add app="^Rust Rover$" title="^(Run Target)$" manage=off
yabai -m rule --add app="^Rust Rover$" title="^(Run/Debug Configurations)$" manage=off

yabai -m rule --add app="^Loopback"$" manage=off


yabai -m rule --add app="^(哔哩哔哩)$" title!="^(哔哩哔哩 \(゜-゜\)つロ 干杯~-bilibili)$" manage=off layer=above

echo "yabai configuration loaded.."
