#!/bin/bash

options=(
	style=round
	#style=square
	width=5.0
	hidpi=off
	#active_color=0xff3D465E
	#inactive_color=0xff3D465E
	#background_color=0xff3D465E

	active_color=0xff8aadf4
	inactive_color=0xff414550

	#active_color=0xc0e2e2e3
	#inactive_color=0xc02c2e34
	#background_color=0x302c2e34
)

borders "${options[@]}"
